// Package shadcntempl ports the shadcn/ui design system to Go + templ + Tailwind v4.
//
// Components live in subpackages (button, table, card, badge, input, ...).
// Each component exposes a Props struct and one or more templ.Component
// functions whose API mirrors the shadcn/ui React equivalent (variant + size
// enums, optional class override, htmx-friendly attribute pass-through).
//
// Styling is driven by Tailwind v4 utilities backed by CSS custom properties.
// The token surface (--background, --foreground, --primary, --radius, ...)
// matches shadcn 2.x and accepts theme presets generated by
// https://ui.shadcn.com/create — see cmd/shadcntempl-theme for the importer.
package shadcntempl
