// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/sbengtson/budget/internal/web/components/ui/button"
	"github.com/sbengtson/budget/internal/web/components/ui/buttongroup"
)

// FirstRunPage is what a brand-new user sees instead of an empty budget. There
// is nothing to assign until money exists somewhere, so the screen asks for one
// thing and nothing else: the account you spend from most.
//
// The form posts to the same /accounts endpoint as the normal account sheet and
// carries first_run=1, which tells the handler to redirect into the budget
// rather than closing a modal that was never open.
func FirstRunPage(month string, collapsed bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex max-w-[620px] flex-col gap-s6 p-s8\"><div class=\"flex flex-col gap-s3\"><span class=\"text-[12px] font-bold uppercase tracking-[0.08em] text-muted-foreground\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(formatMonth(month))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/budget_firstrun.templ`, Line: 20, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><h1 class=\"font-heading text-[34px] font-semibold leading-[1.15]\">Let&#39;s find out what your money is doing.</h1><p class=\"text-[17px] leading-[1.55] text-muted-foreground\">Add the account you spend from most. Pigglet gives you a starter set of categories, and you can assign your first month straight away.</p></div><form hx-post=\"/accounts\" hx-swap=\"none\" class=\"flex max-w-[420px] flex-col gap-s4\"><input type=\"hidden\" name=\"first_run\" value=\"1\"><div class=\"flex flex-col gap-1\"><label for=\"fr-name\" class=\"text-[12px] font-semibold text-muted-foreground\">Account name</label> <input id=\"fr-name\" type=\"text\" name=\"name\" required autofocus autocomplete=\"off\" placeholder=\"Main Checking\" class=\"h-9 w-full rounded-pill border border-input bg-surface-sunk px-s3 text-[15px] outline-none focus-visible:border-primary\"></div><div class=\"flex flex-col gap-1\"><span class=\"text-[12px] font-semibold text-muted-foreground\">Type</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = buttongroup.ButtonGroup(buttongroup.Props{
				ID:    "fr-type",
				Name:  "type",
				Value: "checking",
				Class: "rounded-pill",
				Options: []buttongroup.Option{
					{Value: "checking", Label: "Checking"},
					{Value: "savings", Label: "Savings"},
					{Value: "credit", Label: "Credit"},
					{Value: "loan", Label: "Loan"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"flex flex-col gap-1\"><label for=\"fr-balance\" class=\"text-[12px] font-semibold text-muted-foreground\">What&#39;s in it today</label> <input id=\"fr-balance\" type=\"text\" name=\"starting_balance\" inputmode=\"decimal\" autocomplete=\"off\" placeholder=\"0.00\" class=\"h-9 w-[180px] rounded-pill border border-input bg-surface-sunk px-s3 text-right text-[15px] tabular-nums outline-none focus-visible:border-primary\"> <span class=\"text-[13px] text-muted-foreground\">On a card or loan, enter what you owe as a positive number — Pigglet keeps the sign right.</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "Add account and start")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = button.Button(button.Props{Type: "submit", Class: "h-10 w-full rounded-pill"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Welcome", "budget", collapsed).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
