/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicAuthPathRouteImport } from './routes/_public/auth/$path'
import { Route as AuthedSettingsPathRouteImport } from './routes/_authed/settings/$path'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthPathRoute = PublicAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedSettingsPathRoute = AuthedSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/accounts': typeof AuthedAccountsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings/$path': typeof AuthedSettingsPathRoute
  '/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/accounts': typeof AuthedAccountsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings/$path': typeof AuthedSettingsPathRoute
  '/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/settings/$path': typeof AuthedSettingsPathRoute
  '/_public/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/dashboard'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/accounts'
    | '/_authed/dashboard'
    | '/_public/'
    | '/_authed/settings/$path'
    | '/_public/auth/$path'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/$path': {
      id: '/_public/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof PublicAuthPathRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/settings/$path': {
      id: '/_authed/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof AuthedSettingsPathRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsPathRoute: typeof AuthedSettingsPathRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsPathRoute: AuthedSettingsPathRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthPathRoute: typeof PublicAuthPathRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthPathRoute: PublicAuthPathRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
